#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
#mybatis.type-aliases-package=com.cmd.kafka.mybatis.entity
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: chen1213

# 指定kafka server的地址，集群配多个，中间，逗号隔开
  kafka:
    bootstrap-servers: 192.168.107.128:9092
    producer:
      #重试次数
      retries: 3
      #批量发送的消息数量
      batch-size: 1000
      #32MB的批处理缓冲区
      buffer-memory: 33554432
      #默认消费者组
    consumer:
      group-id: crm-microservice-newperformance
      #最早未被消费的offset
      auto-offset-reset: earliest
      #批量一次最大拉取数据量
      max-poll-records: 4000
      #是否自动提交
      enable-auto-commit: true
      #自动提交时间间隔，单位ms
      auto-commit-interval: 1000

